import { Clock, Home, Image as ImageIcon, Star, Trash2 } from "lucide-react";

export const MOCK_FILES_INITIAL = [
	{
		id: "1",
		parentId: null,
		name: "Documents",
		type: "folder",
		size: "--",
		date: "2023-10-24",
		starred: true,
		isTrashed: false,
	},
	{
		id: "2",
		parentId: null,
		name: "Images",
		type: "folder",
		size: "--",
		date: "2023-11-02",
		starred: false,
		isTrashed: false,
	},
	{
		id: "3",
		parentId: null,
		name: "Work Projects",
		type: "folder",
		size: "--",
		date: "2023-09-15",
		starred: true,
		isTrashed: false,
	},
	{
		id: "4",
		parentId: null,
		name: "Budget_2024.xlsx",
		type: "file",
		fileType: "excel",
		size: "24 KB",
		date: "2023-12-01",
		starred: false,
		isTrashed: false,
	},
	{
		id: "5",
		parentId: null,
		name: "Resume.pdf",
		type: "file",
		fileType: "pdf",
		size: "450 KB",
		date: "2024-01-10",
		starred: true,
		isTrashed: false,
	},
	{
		id: "6",
		parentId: "1",
		name: "Notes.txt",
		type: "file",
		fileType: "text",
		size: "2 KB",
		date: "2023-10-25",
		starred: false,
		isTrashed: false,
	},
	{
		id: "7",
		parentId: "1",
		name: "Report.docx",
		type: "file",
		fileType: "word",
		size: "1.2 MB",
		date: "2023-10-26",
		starred: false,
		isTrashed: false,
	},
	{
		id: "8",
		parentId: "2",
		name: "Vacation",
		type: "folder",
		size: "--",
		date: "2023-11-05",
		starred: false,
		isTrashed: false,
	},
	{
		id: "9",
		parentId: "2",
		name: "Profile_Pic.jpg",
		type: "file",
		fileType: "image",
		size: "2.4 MB",
		date: "2023-11-02",
		starred: false,
		isTrashed: false,
	},
	{
		id: "10",
		parentId: "8",
		name: "Beach.png",
		type: "file",
		fileType: "image",
		size: "3.1 MB",
		date: "2023-11-05",
		starred: false,
		isTrashed: false,
	},
];

export const MOCK_ALBUMS_INITIAL = [
	{ id: "alb1", name: "Vacation 2023", coverId: "10", fileIds: ["10"] },
];

export const SIDEBAR_ITEMS = [
	{ id: "my-files", icon: Home, label: "My Files" },
	{ id: "recent", icon: Clock, label: "Recent" },
	{ id: "gallery", icon: ImageIcon, label: "Gallery" },
	{ id: "starred", icon: Star, label: "Starred" },
	{ id: "trash", icon: Trash2, label: "Trash" },
];
